Profile Mobile Version PR001
Doheera-kosi/Profile-Mobile-Version pull request #1
Opened 2022-08-18 20:47 UTC by Doheera-kosi

Install linters
Incorporate .gitignore
Create/edit index.html and styles.css
Add relevant icon images to the working directory
Create/edit README.md
Modify index.html and styles.css for linter compliance

2022-08-18 21:17 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Doheera-kosi 👋🏻
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍🏻 

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 

## Required Changes:
- [ ] Kindly change the branch's name to make it descriptive of a feature or an action (Example: 'created-mobile-headline'). Please check this [link](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to learn how to do it from github 👍🏻 

_Please check the comments below for more required changes_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:17 UTC, ha-manel commented on README.md
>  > Description the project.
- [ ] Kindly fill out all the sections of the README file to have professional documentation of your project. Copying the template as it is tells us nothing about the project and the work you've done 😄

2022-08-18 21:17 UTC, ha-manel commented on index.html
> +                    </p>
- [ ] Kindly change the `p` tag to `a` tag for the logo. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info ✍🏻

2022-08-18 21:17 UTC, ha-manel commented on index.html
> +                </div>
- [ ] Kindly change the `div` to a `nav` tag for the hamburger menu for semantic reasons 💯

2022-08-18 21:17 UTC, ha-manel commented on index.html
> +                    </div>
- [ ] Kindly wrap the icons in a `ul` element, each icon should be an `a` tag inside an `li` element 👍🏻

2022-08-18 21:17 UTC, ha-manel commented on style.css
> +  font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
- [ ] Kindly try to follow the Figma design as much as possible, please use the same font and the same margins used in Figma

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185494440-da456934-1fcc-455a-b4c4-44c67e60fb7c.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185494495-543e9f93-cba5-4c7b-ac5c-476228041d17.png)

2022-08-18 21:17 UTC, ha-manel commented on style.css
> +html {
- [ ] There is a white space on the top and on the left of your website, kindly fix this error.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185494823-c409b5ea-11e1-436f-b49c-91a114c8df74.png)

2022-08-18 21:17 UTC, ha-manel commented on style.css
> +}
- [ ] Kindly follow the same font family, font size, and text aligning in the Figma design.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185495357-0952eb09-377a-4386-acc1-257a0576f690.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185495301-6b4f635b-193d-4d0f-8b9f-39a6b9c372a4.png)

2022-08-18 21:17 UTC, ha-manel commented on style.css
> +}
- [ ]  Kindly follow the same font family and font size in the Figma design.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185495674-13d1b629-8ab7-4a99-b8e3-e2c56dbff0d5.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185495717-cd7d9324-3a85-4b5c-aa86-112e7a97ff23.png)

2022-08-18 21:17 UTC, ha-manel commented on style.css
> +}
- [ ] Kindly fix your design to make it match the Figma design 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185496149-7b38bac8-0f9a-435b-9555-8fa04a10d328.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185496210-01aa11db-28f2-44f9-8423-8b268a477c5f.png)

2022-08-19 21:05 UTC, closed without merging

2022-08-19 23:55 UTC, mgmediaweb commented on README.md
>  > Description the project.
Good job following the advice of the previous reviewer.

2022-08-20 00:03 UTC, mgmediaweb reviewed
Hi  @Doheera-kosi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![work5](https://user-images.githubusercontent.com/41912912/185721058-d9dcb89f-9391-4a6d-bec6-27a27ce7d3d1.gif)

 ## Highlights 💯 

- Good job following the advice of the previous reviewer.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

[OPTIONAL]  Kindly, you should check a blank space that forms at the top and left of your site, as well as a horizontal scroll that is not recommended, I know you can do better!

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 00:03 UTC, mgmediaweb commented on index.html
> +                    </p>
Kindly, I recommend you to follow the advice of the previous reviewer, it will help you a lot to make your site look and work better.

2022-08-20 00:03 UTC, mgmediaweb commented on index.html
> +                </div>
Kindly, I recommend you to follow the advice of the previous reviewer, it will help you a lot to make your site look and work better.

2022-08-20 00:03 UTC, mgmediaweb commented on index.html
> +                    </div>
Kindly, I recommend you follow the advice of the previous reviewer, it will help you a lot to make your site look and work better.

2022-08-20 00:03 UTC, mgmediaweb commented on style.css
> +  font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
Good job following the advice of the previous reviewer.

2022-08-20 00:03 UTC, mgmediaweb commented on style.css
> +}
Good job following the advice of the previous reviewer.

2022-08-20 00:03 UTC, mgmediaweb commented on style.css
> +}
Good job following the advice of the previous reviewer.

2022-08-20 00:03 UTC, mgmediaweb commented on style.css
> +}
Good job following the advice of the previous reviewer.

2022-08-20 23:25 UTC, bimbolabuari reviewed
Hello @Doheera-kosi  👋,

_This is an additional review as a result of the second opinion request._

- I noticed that you already opened a new PR and got a review on it before requesting a second opinion, Let's remember to always use just one PR for re-review 👍 

Keep rocking 🚀!

2022-08-22 09:54 UTC, prolajumokeoni reviewed
Hi @Doheera-kosi  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a closed pull request, kindly submit an open pr 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._